agent: claude_code_pangu_new
environment: docker-python3.12-uv-host
prompt: just-solve
save_template: "${model.name}/${agent.type}-${agent.version}_baseline_${now:%Y%m%dT%H%M}"

model:
  provider: pangu
  name: pangu

problems:
  - dag_execution
  - dynamic_buffer
  - dynamic_config_service_api
  - execution_server
  - file_backup
  - file_merger
  - metric_transform_lang
  - mocked_http
  - recli
  - sheeteval
  - test_translator
  - textdrop
