agent: claude_code_pangu_new
environment: docker-python3.12-uv-host
prompt: just-solve
save_template: "${model.name}/${agent.type}-${agent.version}_baseline_${now:%Y%m%dT%H%M}"

model:
  provider: pangu
  name: pangu

problems:
  - dynamic_buffer
  - dynamic_config_service_api
  - file_backup
  - metric_transform_lang
  - mocked_http
  - mvvault
  - recli
  - sheeteval
  - test_translator
  - textdrop
  - trajectory_api
